# --------- Dev Stage ---------
FROM node:20 AS dev
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY ./src ./src
COPY vite.config.js ./
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host"]

# --------- Runtime Stage ---------
FROM nginx:alpine AS runtime
COPY nginx.conf /etc/nginx/nginx.conf
WORKDIR /usr/share/nginx/html
COPY dist .
CMD ["nginx", "-g", "daemon off;"]
