spring.application.name=backend

jwt.access-token-secret=MySuperSecretKeyThatIsAtLeast32CharactersLong!!
jwt.refresh-token-secret=AnotherSuperSecretKeyThatIsAlso32Chars!!
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=604800000

#decouple database - enable dbconfig
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration